export enum CartActionTypes {
  ADD_PIZZA_CART = 'ADD_PIZZA_CART',
  CLEAR_CART = 'CLEAR_CART',
  REMOVE_CART_ITEM = 'REMOVE_CART_ITEM',
  PLUS_CART_ITEM = 'PLUS_CART_ITEM',
  MINUS_CART_ITEM = 'MINUS_CART_ITEM',
}
